### ISSUE TITLE
Minor issue with long TBLPATH 

### ISSUE THREAD

**Issue by rtfisher** [jschwab/python-helmholtz#1]
For TBLPATH > 132 characters, one obtains "Error: Line truncated at (1) [-Werror=line-truncation]" on line 27 in helmholtz.f90. Suggested fix to Makefile:

helmholtz.o : helmholtz.f90
        ${FC} -cpp -DTBLPATH="'${HELM_TABLE_DIR}/${HELM_TABLE_NAME}'" -ffree-line-length-none -c -fPIC $<

**Comment by jschwab** [comment]
Thanks!
