### ISSUE TITLE
f2py

### ISSUE THREAD

**Issue by joshuashzha** [jschwab/python-helmholtz#2]
Hi, Josh. It seems that in Makefile f2py should be f2py3? It failed when using f2py as it used python2, though I am not sure why as I am not familiar with python compiler in Ubuntu. Do you have any idea?
Thanks,
Shuai

**Comment by jschwab** [comment]
The executable naming varies between systems.  For example, on my machine f2py is the python3 version and the f2py2 is python2.   Off the top of my head, I'm not sure what else to do except add a note to the docs (and maybe make it a variable in the Makefile).

**Comment by joshuashzha** [comment]
Thanks. Yes, the alias could be different. Maybe just add a note in readme.
