### ISSUE TITLE
Generating the Helmholtz Table

### ISSUE THREAD

**Issue by Carlson-J** [jschwab/python-helmholtz#3]
It is not clear in your documentation on how to generate the table you are interpolating over. If I want to make a table that has the true values (or as close as I can get numerically) how would I do that?

**Comment by jschwab** [comment]
The underlying Helmholtz table comes from Frank Timmes:  http://cococubed.asu.edu/code_pages/eos.shtml and is described in this article: https://ui.adsabs.harvard.edu/abs/2000ApJS..126..501T/abstract

**Comment by Carlson-J** [comment]
Ok, so to confirm, the Helmholtz table values come from the values generated by the timmes eos, which is wrapped by the helmholtz.eosfxt python function in your code?

**Comment by jschwab** [comment]
Yes, that's the relation between helmholtz/timmes(eosfxt) for the electron-positron part of the EOS.
